algoritmo "semnome"
// Função :
// Autor :
// Data : 03/05/2023
// Seção de Declarações 
var
n1, n2, n3, n4, n5:real
inicio
// Seção de Comandos 
escreval (" digite 1 número:")
leia (n1)
n1<-(n1*n1)
escreval (" digite 1 número:")
leia (n2)
n2<-(n2*n2)
escreval (" digite 1 número:")
leia (n3)
n3<-(n3*n3)
escreval (" digite 1 número:")
leia (n4)
n4<-(n4*n4)
n5<-(n1+n2+n3+n4)
escreva (n1, n2, n3, n4, " e a soma deles é: ",n5)
fimalgoritmo
